apiVersion: apps/v1
kind: Deployment
metadata:
  name: progate-lion-hackathon-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: progate-lion-hackathon-app
  template:
    metadata:
      labels:
        app: progate-lion-hackathon-app
    spec:
      containers:
        - name: progate-lion-hackathon-app
          image: 192730322953.dkr.ecr.us-west-2.amazonaws.com/alive-talk:18bfb95ae28ee6a1f1f61d63c0df9b36301af024
          ports:
            - containerPort: 3000
