apiVersion: apps/v1
kind: Deployment
metadata:
  name: progate-lion-hackathon-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: progate-lion-hackathon-app
  template:
    metadata:
      labels:
        app: progate-lion-hackathon-app
    spec:
      containers:
        - name: progate-lion-hackathon-app
          image: 192730322953.dkr.ecr.us-west-2.amazonaws.com/alive-talk:62a6d522064e056946789476d5d5ba1a7a1e5d73
          ports:
            - containerPort: 3000
