apiVersion: apps/v1
Kind: Deployment
metadata:
  name: progate-lion-hackathon-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: progate-lion-hackathon-app
  template:
    metadata:
      labels:
        app: progate-lion-hackathon-app
    spec:
      containers:
        - name: progate-lion-hackathon-app
          image: 192730322953.dkr.ecr.us-west-2.amazonaws.com/alive-talk:b3f8024c3e7fc3e90db409048b76084328eb030c
          ports:
            - containerPort: 3000
