apiVersion: apps/v1
kind: Deployment
metadata:
  name: progate-lion-hackathon-app
  labels:
    app: progate-lion-hackathon-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: progate-lion-hackathon-app
  template:
    metadata:
      labels:
        app: progate-lion-hackathon-app
    spec:
      containers:
        - name: progate-lion-hackathon-app
          image: 192730322953.dkr.ecr.us-west-2.amazonaws.com/alive-talk:a89d94924bf97f2b07a3738a4ab680499485d1aa
          command: ["yarn", "run", "dev"]
          ports:
            - containerPort: 3000
