apiVersion: apps/v1
kind: Deployment
metadata:
  name: progate-lion-hackathon-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: progate-lion-hackathon-app
  template:
    metadata:
      labels:
        app: progate-lion-hackathon-app
    spec:
      containers:
        - name: progate-lion-hackathon-app
          image: 192730322953.dkr.ecr.us-west-2.amazonaws.com/alive-talk:a33aa71ddf0d571f6d03f522f7237a2d3d416fde
          ports:
            - containerPort: 3000
