apiVersion: v1
kind: Service
metadata:
  name: progate-lion-hackathon-service
  namespace: default
  labels:
    app: progate-lion-hackathon-app
spec:
  selector:
    app: progate-lion-hackathon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
